CREATE DATABASE IF NOT EXISTS DIGITAL_LIBRARY_SYSTEM;
USE DIGITAL_LIBRARY_SYSTEM;

CREATE TABLE IF NOT EXISTS LIBRARY_BOOKS (
    BOOK_ID INT PRIMARY KEY,
    BOOK_TITLE VARCHAR(100),
    GENRE VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS LIBRARY_MEMBERS (
    MEMBER_ID INT PRIMARY KEY,
    MEMBER_NAME VARCHAR(100),
    LAST_BORROW_DATE DATE
);

CREATE TABLE IF NOT EXISTS BOOK_TRANSACTIONS (
    TRANSACTION_ID INT PRIMARY KEY,
    BOOK_ID INT,
    MEMBER_ID INT,
    BORROW_DATE DATE,
    RETURN_DATE DATE,
    FOREIGN KEY (BOOK_ID) REFERENCES LIBRARY_BOOKS(BOOK_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES LIBRARY_MEMBERS(MEMBER_ID)
);

INSERT IGNORE INTO LIBRARY_BOOKS VALUES
(1, 'JAVA', 'EDUCATION'),
(2, 'PYTHON', 'EDUCATION'),
(3, 'SQL', 'EDUCATION'),
(4, 'PHYSICS', 'SCIENCE');

INSERT IGNORE INTO LIBRARY_MEMBERS VALUES
(101, 'LOUKHYA', '2025-01-15'),
(102, 'MOULYA', '2025-11-14'),
(103, 'HEMA', '2025-06-30');

INSERT IGNORE INTO BOOK_TRANSACTIONS VALUES
(1, 1, 101, '2025-01-20', NULL),
(2, 2, 102, '2025-11-25', '2025-04-05');

-- Find overdue books and calculate fine
SELECT
    M.MEMBER_NAME,
    B.BOOK_TITLE,
    T.BORROW_DATE,
    GREATEST(DATEDIFF(CURDATE(), T.BORROW_DATE) - 14, 0) AS LATE_DAYS,
    GREATEST(DATEDIFF(CURDATE(), T.BORROW_DATE) - 14, 0) * 5 AS FINE_AMOUNT
FROM BOOK_TRANSACTIONS T
JOIN LIBRARY_MEMBERS M ON T.MEMBER_ID = M.MEMBER_ID
JOIN LIBRARY_BOOKS B ON T.BOOK_ID = B.BOOK_ID
WHERE T.RETURN_DATE IS NULL
  AND T.BORROW_DATE < CURDATE() - INTERVAL 14 DAY;

-- Category-wise borrowing report
SELECT
    B.GENRE,
    COUNT(*) AS BOOKS_ISSUED
FROM BOOK_TRANSACTIONS T
JOIN LIBRARY_BOOKS B ON T.BOOK_ID = B.BOOK_ID
GROUP BY B.GENRE
ORDER BY BOOKS_ISSUED DESC;

-- Remove inactive members (not borrowed for 3 years)
SET SQL_SAFE_UPDATES = 0;

DELETE FROM LIBRARY_MEMBERS
WHERE LAST_BORROW_DATE < CURDATE() - INTERVAL 3 YEAR;

SET SQL_SAFE_UPDATES = 1;